//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPSSOnlineRecruitmentPortal.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NPSSEntities : DbContext
    {
        public NPSSEntities()
            : base("name=NPSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicantExperienceDetail> ApplicantExperienceDetails { get; set; }
        public virtual DbSet<ApplicantQualificationDetail> ApplicantQualificationDetails { get; set; }
        public virtual DbSet<AsstAOApplicationID> AsstAOApplicationIDs { get; set; }
        public virtual DbSet<QualificationHeader> QualificationHeaders { get; set; }
        public virtual DbSet<QualificationType> QualificationTypes { get; set; }
        public virtual DbSet<SupervisorApplicationID> SupervisorApplicationIDs { get; set; }
        public virtual DbSet<EmailFailureBacklog> EmailFailureBacklogs { get; set; }
        public virtual DbSet<ApplicantMaster> ApplicantMasters { get; set; }
    
        public virtual int DeleteApplicantDetails(Nullable<int> applicantID)
        {
            var applicantIDParameter = applicantID.HasValue ?
                new ObjectParameter("ApplicantID", applicantID) :
                new ObjectParameter("ApplicantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteApplicantDetails", applicantIDParameter);
        }
    
        public virtual int UpdateApplicationIDByPost(Nullable<int> applicantID, Nullable<int> post)
        {
            var applicantIDParameter = applicantID.HasValue ?
                new ObjectParameter("ApplicantID", applicantID) :
                new ObjectParameter("ApplicantID", typeof(int));
    
            var postParameter = post.HasValue ?
                new ObjectParameter("Post", post) :
                new ObjectParameter("Post", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateApplicationIDByPost", applicantIDParameter, postParameter);
        }
    
        public virtual ObjectResult<SP_ExpierienceDetail_Result> SP_ExpierienceDetail(Nullable<int> applicantID)
        {
            var applicantIDParameter = applicantID.HasValue ?
                new ObjectParameter("ApplicantID", applicantID) :
                new ObjectParameter("ApplicantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ExpierienceDetail_Result>("SP_ExpierienceDetail", applicantIDParameter);
        }
    
        public virtual ObjectResult<SP_GetApplicationDetail_Result> SP_GetApplicationDetail(Nullable<int> applicantID)
        {
            var applicantIDParameter = applicantID.HasValue ?
                new ObjectParameter("ApplicantID", applicantID) :
                new ObjectParameter("ApplicantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetApplicationDetail_Result>("SP_GetApplicationDetail", applicantIDParameter);
        }
    
        public virtual int SP_QualificationDetail(Nullable<int> applicantID)
        {
            var applicantIDParameter = applicantID.HasValue ?
                new ObjectParameter("ApplicantID", applicantID) :
                new ObjectParameter("ApplicantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_QualificationDetail", applicantIDParameter);
        }
    }
}
