//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPSSOnlineRecruitmentPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationType
    {
        public int QualificationTypeID { get; set; }
        public string QualificationType1 { get; set; }
        public bool IsRequired { get; set; }
    }
}
