//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPSSOnlineRecruitmentPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorApplicantMaster
    {
        public int SApplicantID { get; set; }
        public string ApplicantSeatNumber { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime AgeOnApplicationDate { get; set; }
        public string BirthPlaceVillage { get; set; }
        public string BirthPlaceCity { get; set; }
        public string BirthPlaceState { get; set; }
        public string BirthPlaceCountry { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public int MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string Cast { get; set; }
        public string SubCast { get; set; }
        public string ImagePath { get; set; }
    }
}
